name: Create or Update Single Animation in Aseprite File for {game_object}
description: Template for creating or updating a single animation in a .aseprite file.
title: "Create or Update Animation for {game_object}"
labels: ["art", "2d art", "animation", "2d animation", "aseprite"]
body:
  - type: input
    id: animation_name
    attributes:
      label: Animation Name
      description: Provide the name of the animation to be created or updated.
      placeholder: "Enter the animation name, e.g., 'walk_right'..."
      value: "walk_right"
    validations:
      required: true

  - type: textarea
    id: animation_description
    attributes:
      label: Animation Description
      description: Provide a brief description of the animation and its purpose.
      placeholder: "Enter the animation description..."
      value: "Walks right - smooth 8-frame cycle."
    validations:
      required: true

  - type: input
    id: file_path
    attributes:
      label: Save File Path
      description: Provide the directory path where the .aseprite file is located or should be saved.
      placeholder: "Enter the full file path, e.g., game/{game_object}/{game_object}/animations..."
      value: "game/{sub_directory}/{game_object}/{game_object}.aseprite"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria:

        - [ ] An .aseprite file is created or updated and saved in the correct directory: `game/{sub_directory}/{game_object}/{game_object}.aseprite`.
        - [ ] The specified animation is added or updated as a tag in the .aseprite file.
        - [ ] Tags for one-shot animations are configured with `repeat: 1`.
        - [ ] Files follow naming conventions: lowercase, underscore-separated, no spaces.
        - [ ] A pull request (PR) is created with the updated .aseprite file and accompanying `.import` file.

        [Pull Request Guide: Github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

  - type: textarea
    validations:
      required: true
    attributes:
      id: subtasks
      label: Subtasks
      value: |
        - [ ] Create or update the .aseprite file with the specified animation.
        - [ ] Add the animation as a tag in the .aseprite file.
        - [ ] Configure one-shot tags with `repeat: 1` where applicable.
        - [ ] Ensure the .aseprite file is saved in the correct directory: `game/{sub_directory}/{game_object}/{game_object}.aseprite`.
        - [ ] Ensure files follow naming conventions: lowercase, underscore-separated, no spaces.
        - [ ] Submit a pull request with the updated .aseprite file, `.import` file (if Godot generates one), and all changes.

        [Pull Request Guide: Github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
