name: Cyclomatic Complexity Check

on:
  pull_request:
    paths:
      - '**/*.gd'

permissions:
  pull-requests: write

concurrency:
  group: cyclomatic-cc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cyclomatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Find changed GDScript files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: '**/*.gd'
          files_ignore: 'addons/**'

      - name: Early exit if no GD files changed
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No GDScript files changed, skipping complexity check"

      - name: Save changed files list
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}" \
            | tr ' ' '\n' > gd_script_files.txt

      - name: Set up Python (with pip cache)
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            **/pyproject.toml
            **/setup.py

      - name: Install gdtoolkit (for gdradon CLI)
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pip install --no-warn-script-location gdtoolkit==4.*

      - name: Run Cyclomatic Complexity Analysis
        if: steps.changed-files.outputs.any_changed == 'true'
        id: cc
        run: |
          # filter out addons and build an array of files
          files=$(grep -v '^addons/' gd_script_files.txt | tr '\n' ' ')
          # run gdradon cc in JSON mode
          report=$(gdradon cc $files --format json 2>&1)
          exit_code=$?
          # expose both JSON and exit code
          {
            echo "cc_output<<EOF"
            echo "$report"
            echo "EOF"
            echo "exit_code=$exit_code"
          } >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Comment PR with Complexity Report
        if: steps.changed-files.outputs.any_changed == 'true' && steps.cc.outputs.cc_output != ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: cyclomatic-complexity-check
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 📊 Cyclomatic Complexity Report
            ${{ steps.cc.outputs.exit_code == '0' && '✅ Complexity within acceptable bounds' || '❌ Complexity thresholds exceeded' }}

            <details>
            <summary>View full report ( ${{ steps.changed-files.outputs.all_changed_files_count }} files )</summary>

            ```json
            ${{ steps.cc.outputs.cc_output }}
            ```
            </details>
